[tox]
envlist = linters,typecheck,unit-tests
requires =
    tox>=4
skipsdist=True

[testenv]
deps = 
    weatherrouting
    requests
    colorlog
    geojson_utils
    pynmea2
    pyserial
    gpxpy
    pyais
commands =
    python -I -m build --wheel -C=--build-option=-- -C=--build-option=-- -C=--build-option=-j4


[testenv:coverage]
allowlist_externals = bash
deps =
    {[testenv]deps}
    pytest
    pytest-cov
    parameterized
commands_pre =
    bash -c 'pip install gdal[numpy]==$(gdal-config --version).*'
commands =
    pytest --cov-report term-missing --cov-report html --cov-report xml --cov=gweatherrouting


[testenv:unit-tests]
allowlist_externals = bash
deps =
    {[testenv]deps}
    pytest
    parameterized
commands_pre =
    bash -c 'pip install gdal[numpy]==$(gdal-config --version).*'
commands =
    pytest #-rP


[testenv:flake8]
deps =
    ; {[testenv]deps}
    flake8
    pep8-naming
commands =
    flake8 ./gweatherrouting

[testenv:isort]
deps =
    ; {[testenv]deps}
    isort
commands =
    isort .

[testenv:black]
deps =
    ; {[testenv]deps}
    black[jupyter]
commands =
    black .

[testenv:typecheck]
; allowlist_externals = mypy # TODO: why?
deps =
    ; {[testenv]deps}
    mypy
    types-setuptools
    types-requests
    types-python-dateutil
commands =
    mypy ./gweatherrouting

[testenv:linters]
deps =
    #{[testenv:isort]deps}
    {[testenv:black]deps}
    {[testenv:flake8]deps}
commands =
    #{[testenv:isort]commands}
    {[testenv:black]commands}
    {[testenv:flake8]commands}

