MDScreen:
    MDBoxLayout:
        orientation: 'vertical'

        MDToolbar:
            title: "GWR"
            md_bg_color: app.theme_cls.accent_color
            right_action_items: [["dots-vertical", lambda x: app.callback()]]
            left_action_items: [["menu", lambda x: app.callback()]]

        MapView
            id: mapView
            zoom:   8
            lat:    39
            lon:    9