#:kivy 1.0

<RegattaScreen>:
    MDTabs:
        Tab:
            title: "Map"
            content_text: f"This is an example text for {self.title}"

        Tab:
            title: "Gauges"
            content_text: f"This is an example text for {self.title}"

        Tab:
            title: "Logs"
            content_text: f"This is an example text for {self.title}"

        Tab:
            title: "Parameters"
            content_text: f"This is an example text for {self.title}"

        