name: AppImage
# on: [push]

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: AppImage
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ubuntu Dependencies
        run: |
            bash .github/workflows/script/ubuntu_dep.sh

      - name: Install Python Dependencies
        run: |
            bash .github/workflows/script/python_dep.sh
      - name: Instal gww
        run: pip install .

      - name: Generate AppImage
        run: |
            pip install pyinstaller
            cd appimage
            bash appimagegen.sh -y

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
            name: GWeatherRouting-linux-x86_64.appimage
            path: ${{ github.workspace }}/**/*.AppImage
